---
title: "Resources for humanities and social sciences (HSS)"
aliases:
  - /domains/dh
toc: false
---

Annual [Digital Humanities Summer Institute](http://www.dhsi.org) at the University of Victoria offers courses
on research computing topics in humanities and social sciences. Some of DHSI courses each year are taught by
our analysts and staff.

* "3D visualization for the humanities": [ZIP file](http://bit.ly/dhfileszip) with slides, scripts, and data
  files

## Webinars

<!-- <details> -->
<!-- <summary style="line-height: 0.6; margin: 0; padding: 2px 0;"> -->
<!-- <span style="font-size: 1.2em;">title</span> (date) -->
<!-- </summary> -->
<!-- <br> -->
<!-- <p> -->
<!-- paragraph 1 -->
<!-- </p><p> -->
<!-- paragraph 2 -->
<!-- </p> -->
<!-- <ul> -->
<!-- 	<li>Speaker: </li> -->
<!-- 	<li><a href="" target="_blank">PDF slides</a></li> -->
<!-- </ul> -->
<!-- <div class="video-container" data-url="https://www.youtube.com/embed/videoIDstring"></div> -->
<!-- <br> -->
<!-- </details> -->

Click on each webinar for its recording and materials.

<details>
<a name="photogrammetry"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Photogrammetry on HPC clusters</span> (2024-Feb-20)
</summary>
<br>
<p>
The term <i>photogrammetry</i> typically refers to the process of constructing a 3D model by analyzing a series of
photographs of the same subject captured from various angles. Widely employed in fields such as mapping,
surveying, architecture, archaeology, and cultural heritage preservation, photogrammetry is very expensive
computationally and is traditionally done with commercial packages, even on large workstations and HPC
clusters. Regrettably, in the eyes of many academic researchers, open-source photogrammetry tools have still
not caught up with proprietary software in terms of both performance and output quality. Even further, running
open-source photogrammetry on HPC clusters is far from trivial. In this webinar, we demonstrate a couple of
photogrammetry workflows that we have run successfully on Cedar. We take a look at OpenDroneMap and Meshroom
and discuss all steps from taking initial images to building and displaying a final 3D textured model.
</p>
<ul>
	<li>Speaker: Alex Razoumov</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/photogrammetry20240220.pdf" target="_blank">PDF slides</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=JwNKSATAhco width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/JwNKSATAhco"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="text-analysis-in-3d"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Text analysis in 3D</span> (2023-Nov-28)
</summary>
<br>
<p>
3D visualization is surprisingly little used to visualize data and connections in digital humanities, despite
the fact that the 3rd dimension can provide many benefits, from decluttering your plot to encoding one of the
variables. In this webinar I present a workflow to analyze a text corpus consisting of works from multiple
authors, and visualize the differences between their vocabularies in 3D. I complement this visualization with
3D graphs to link similar texts. Throughout this webinar I am using only open-source tools -- Python and
several 3rd-party Python libraries, ParaView, and VTK, and show 3D visualizations that can easily scale to
millions of texts and can work for any input language.
</p>
<ul>
	<li>Speaker: Alex Razoumov</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/texts20231128.pdf" target="_blank">PDF slides</a></li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/texts20231128.zip" target="_blank">All scripts</a> from the presentation (ZIP file)</li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=8kZaCbDvzcU width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/8kZaCbDvzcU"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="regexpchatgpt"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Learning Regular Expressions with Smart Tools</span> (2023-May-09)
</summary>
<br>
<ul>
	<li>Speaker: John Simpson</li>
	<li><a href="https://bit.ly/westdri-regex-may2023" target="_blank">Google Doc</a> (read-only) with links and workshop notes</li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=f8-7MBc8BRs width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/f8-7MBc8BRs"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="exploration"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Exploration of tools and approaches for Humanists</span> (2021-May-12)
</summary>
<br>
<ul>
	<li>Speaker: Megan Meredith-Lobay</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/explorationDH20210512.pdf" target="_blank">PDF slides</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=wLU3dDkLokQ width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/wLU3dDkLokQ"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="twitterapistwo"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Mining Twitter data for research</span> (Part 2, 2020-May-27)
</summary>
<br>
<ul>
	<li>Speaker: John Simpson</li>
	<li><a href="https://github.com/ualberta-rcg/twitter_scraping" target="_blank">Python notebook</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=7H6Plcr6IkM width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/7H6Plcr6IkM"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="twitterapis"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Tips & tools for mining Twitter data for research</span> (Part 1, 2019-Nov-27)
</summary>
<br>
<ul>
	<li>Speaker: John Simpson</li>
	<li><a href="https://github.com/ualberta-rcg/twitter_scraping" target="_blank">Python notebook</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=gy4nUgPBHeM width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/gy4nUgPBHeM"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<a name="textParsing"></a>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Text parsing & matching with HPC resources</span> (2019-Feb-06)
</summary>
<br>
<ul>
	<li>Speaker: Ian Percel</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/textParsing20190206.pdf" target="_blank">PDF slides</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=iH0jxOY3YiI width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/iH0jxOY3YiI"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Getting started on the cloud</span> (2018-Nov-28)
</summary>
<br>
<ul>
	<li>Speaker: John Simpson</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/gettingStartedCloud20181128.pdf" target="_blank">PDF slides</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=dzrzjpXPC6M width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/dzrzjpXPC6M"></div>
<br>
</details>
<!-- ========================================================================================== -->
<details>
<summary style="line-height: 0.6; margin: 0; padding: 2px 0;">
<span style="font-size: 1.2em;">Tools for Handling Big Data & Computing Demands in HSS Research</span> (2017-Sep-21)
</summary>
<br>
<ul>
	<li>Speaker: Megan Meredith-Lobay</li>
	<li><a href="https://raw.githubusercontent.com/WestGrid/trainingMaterials/gh-pages/materials/ccToolsHumanitiesSocialSciences20170921.pdf" target="_blank">PDF slides</a></li>
</ul>
<!-- {{< video https://www.youtube.com/watch?v=5p201-BcVLo width="100%" height="500px" >}} -->
<div class="video-container" data-url="https://www.youtube.com/embed/5p201-BcVLo"></div>
<br>
</details>

<br>
```{=html}
{{< video https://www.youtube.com/watch?v=videoIDstring width="100%" height="500px" >}}
<div class="d-flex justify-content-end my-4">
  <button class="btn btn-outline-secondary btn-sm" onclick="collapseAllDetails()">
    <i class="bi bi-arrows-collapse"></i> Collapse All Sections
  </button>
</div>
<!-- button to collapse all sections in this page -->
<script>
function collapseAllDetails() {
  document.querySelectorAll('details').forEach(d => d.open = false);
}
</script>
<!-- embed a video forcing a high-resolution thumbnail preview -->
<script>
document.querySelectorAll('details').forEach(details => {
  details.addEventListener('toggle', () => {
    if (details.open) {
      const container = details.querySelector('.video-container');
      if (container && !container.querySelector('iframe')) {
        const url = container.getAttribute('data-url');
        container.innerHTML = `<iframe src="${url}" width="100%" height="500px" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`;
      }
    }
  });
});
</script>
```
