---
title: "Events for fall 2021"
aliases:
  - /fall-2021
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain / 12pm
Central. For *upcoming sessions*, click the linked title to see more details or to register. For *past sessions*, click
on the title to view recordings and slides.

| TOPIC | DATE | Speaker |
| ------------- | --------------- | ----------------- |
| [<span style="color:blue">Remote visualization on Compute Canada clusters</span>](/tools/visualization/#remote-visualization-on-compute-canada-clusters) | Sep-29 | Alex Razoumov |
| [<span style="color:blue">Container-based approach to bioinformatics applications</span>](/domains/bioinfo/#container-based-approach-to-bioinformatics-applications) | Oct-13 | Tannistha Nandi |
| [<span style="color:blue">Easier parallel Julia workflow with Dagger.jl</span>](/programming/#julia) | Oct-27 | Marie-Helene Burle |
| [<span style="color:blue">Highlights from the 2021 SciVis Contest</span>](/tools/visualization/#highlights-from-the-2021-scivis-contest) | Nov-10 | Alex Razoumov |
| [<span style="color:blue">Upscaling with PyTorch</span>](/tools/ml/#upscaling-with-pytorch) | Nov-24 | Marie-Helene Burle |
| [<span style="color:blue">Installing software using EasyBuild in your cluster home directory</span>](/getting-started#building-software-with-easybuild) | Dec-08 | Ata Roudgar | <!-- earlier possibilities: HubZero or Databases on Cedar/Graham -->

<!-- Nov-13[^1] -->
<!-- [^1]: Note the different day of the week (Friday). -->

## Other workshops

| Event | DATE | Location |
| ------------- | --------------- | ----------------- |
| [Taking Git one step further - collaborating through GitHub](https://libcal.library.ubc.ca/event/3629630) | Sep-23 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [UofA's Fall Research Computing Bootcamp](https://www.ualberta.ca/information-services-and-technology/news/2021/fall-2021-research-computing-bootcamp.html) | Sep-27 to Oct-25 | Online by the UofA |
| [Visualization with Paraview (EN)](https://www.eventbrite.ca/e/171338226247) | Oct-04 and Oct-05 | <span style="color:#3339ff">National training workshop</span> |
| [Multi-processing in Julia](https://libcal.library.ubc.ca/calendar/vancouver/julia-part-1) | Oct-14 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| Parallel Julia workshop | Oct-18 and Oct-19 | Invited for a 3rd party |
| [Visualization with Paraview (FR)](https://www.eventbrite.ca/e/172208820217) | Nov-02 and Nov-03 | <span style="color:#3339ff">National training workshop</span> |
| [Using Deep Learning to increase image resolution](https://libcal.library.ubc.ca/calendar/vancouver/deep-learning-image-processing) | Nov-18 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [Working with shared and distributed arrays in Julia](https://libcal.library.ubc.ca/calendar/vancouver/julia-part-2) | Dec-09 | <span style="color:#049A80">Online for UBC Research Commons</span> |

<!-- As always, we welcome requests for other training topics and events. Please email suggestions to training@westgrid.ca. -->
