---
title: "Events for fall 2022"
aliases:
  - /fall-2022
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

<!-- While WestGrid ceased its operations on March 31, 2022, research computing training in Western Canada remains -->
<!-- -- coordinated by the same team, now based at Simon Fraser University, with participation from HPC analysts -->
<!-- across the BC DRI Group and the Prairies DRI Group (former WestGrid space). -->

To receive future news and emails about the BC DRI Group and the Prairies DRI Group training events, please
[subscribe here](/contact).

## [Webinars]{#webinars}

BC DRI + Prairies DRI bi-weekly Research Computing webinars take place every second Wednesday at 10am Pacific
/ 11am Mountain / 12pm Central.

<!-- We will open registration in early September. -->
<!-- For *upcoming webinars*, click the linked title to see more details or to register. For *past -->
<!-- sessions*, click on the title to view recordings and slides. -->

| TOPIC | DATE | Speaker |
| ------------- | --------- | ----------------- |
| [<span style="color:blue">In-situ visualization with ParaView Catalyst2</span>](/tools/visualization/#in-situ-visualization-with-paraview-catalyst2) | Sep-28 | Alex Razoumov (SFU) |
| [<span style="color:blue">TensorBoard for objection detection models</span>](/tools/ml/#tensorboard) | Oct-12 | Jillian Anderson (SFU) |
| [<span style="color:blue">Data visualization in Julia with the Makie ecosystem</span>](/tools/visualization/#data-visualization-in-julia-with-the-makie-ecosystem) | Oct-26 | Marie-Hélène Burle (SFU) |
| [<span style="color:blue">Storage options for cloud computing</span>](/tools/virtual#storage-options-for-cloud-computing) | Nov-09 | Sarah Huber (UVic) |
| [<span style="color:blue">Turbo boost your interactive experience on the cluster with tmux</span>](/getting-started#linux) | Nov-23 | Chris Want (UofA) |
| [<span style="color:blue">Lesser known but very useful Bash features</span>](/getting-started#linux) | Dec-07 | Alex Razoumov & <br> Marie-Hélène Burle (SFU) |

<!-- Nov-13[^1] -->
<!-- [^1]: Note the different day of the week (Friday). -->

## [SFU / UBC Research Commons workshops]{#commons}

These workshops are in-person only. Students, staff and faculty are all welcome to attend.
<!-- For upcoming workshops, click a date to see more details or to register. -->
To register, click on an event in the 2nd or 3rd column.

| TOPIC | 1st run | 2nd run |
| ----- | ---------- | ---------- |
| Automation and scripting in bash for absolute beginners | [Friday, Sep-23 at<br> <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3683923) | [Thursday, Sep-29 at<br> <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/37400)
| 1/2-day Git workshop | [Tuesday, Oct-04 at<br> <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/help/publish/research-data-management/37488) |
| What format to choose to save your data | [Thursday, Oct-27 at<br> <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/37399) | [Friday, Nov-04 at<br> <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3683941)
| Authoring scientific documents with Markdown and Quarto | [Thursday, Nov-24 at<br> <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/37398) | [Friday, Dec-02 at<br> <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3683985)

## [Local bootcamps and workshops]{#bootcamps}

| Title | Date | Location |
| ------- | --- | -------- |
| [Fall Research Computing Bootcamp](https://www.ualberta.ca/information-services-and-technology/news/2022/fall-research-computing-bootcamp-starts-september-16.html){target="_blank"} | Sep-16 to Oct-03 | University of Alberta |
| [Workshop: Introduction to machine learning under the Alliance resources](https://onlineacademiccommunity.uvic.ca/rcs/2022/09/09/workshop-introduction-to-machine-learning-under-the-alliance-resources){target="_blank"} | Sep-29 | University of Victoria |

## WestDRI autumn school

In our [2022 autumn school](https://autumnschool2022.westdri.ca){target="_blank"} we decided to focus on a
small subset of our courses, leaving more advanced topics to spring (March) and summer (May-June) schools.

<!-- Registration for the autumn school is [now -->
<!-- open](https://forms.gle/NZhzRU5o8ti8VhVJ7){target="_blank"}. You will need a Canadian academic email address -->
<!-- to register. -->

| Course | Date | Location |
| -- | -- | -- |
| [Linux command line](https://autumnschool2022.westdri.ca/bash-menu){target="_blank"} | Nov-08 | Online |
| [Python level 1](https://autumnschool2022.westdri.ca/python-menu){target="_blank"} | Nov-10 | Online |
| [Intro to HPC](https://autumnschool2022.westdri.ca/hpc-menu){target="_blank"} | Nov-15 | Online |
| [R level 1](https://autumnschool2022.westdri.ca/r-menu){target="_blank"} | Nov-17 | Online |
| [GPU Python (NVIDIA)](https://autumnschool2022.westdri.ca/gpu-menu){target="_blank"} | Nov-22 | Online |

As always, we welcome requests for other training topics and events. Please email suggestions to `training at
westdri dot ca`.
