---
title: "Events for fall 2018"
aliases:
  - /fall-2018
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

For more information on each session, or to register, click on the links below.

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain
/ 12pm Central. Note two off-cycle special dates (Sep-20 and mid-November).

| TOPIC | DATE | Speaker |
| ------------- | ----- | -------- |
| *How to submit and run jobs on Compute Canada HPC systems* | Sep-19 | Alex Razoumov |
| *Arbutus Upgrade: What you need to know* | Sep-20 (**special time**) | Ryan Enge and Venkat Mahadevan |
| *Common job submission errors and how to avoid them* | Oct-03 | Kamil Marcinkowski |
| *Tools for automating analysis pipelines* | Oct-17 | Jamie Rosner |
| *Data Analytics and Machine Learning with MATLAB* | Oct-31 | Sumit Tandon (MathWorks) |
| *How HPC helped researchers simulate the life of a star* | Nov-14 | Falk Herwig (UVic) |
| *Using yt for analysis and visualization of volumetric data* | Nov-21 (alternate week) | Alex Razoumov |
| *Getting started on the cloud* (HSS Part 1) | Nov-28 | John Simpson |
| *How to deploy HTTP and HTTPS sites on a virtual machine* (HSS Part 2) | Dec-12 | John Simpson |

## In-person workshops

| Event | DATE | Location |
| -------------------- | ------ | ---------- |
| [*Research Computing Fall Bootcamp*](https://ist.ualberta.ca/blog/events/get-ready-research-computing-fall-bootcamp) | Sep-24 to 28 | UofA |
| [*Introduction to Python*](https://www.lib.sfu.ca/find/other-materials/data-gis/gis/33694) | Sep-25 | SFU's Big Data Hub |
| [*A taste of parallel programming with Chapel*](https://www.lib.sfu.ca/about/branches-depts/rc/services/workshops/taste-parallel-programming-chapel) | Oct-23 | SFU, Bennett Library, Rm 7010, Research Commons |
| Introductory Research Computing Workshop | Nov-02, 3pm-5pm | University of Manitoba, Department of Biochemistry and Medical Genetics, Basic Medical Science Building, Room 341 |

As always, we welcome requests for other training topics and events. Please email suggestions to info at
westgrid dot ca.
