---
title: "Events for fall 2020"
aliases:
  - /fall-2020
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

<!-- For more information on each session, or to register, click on the links below. -->

<!-- ========================================================================================== -->

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain / 12pm Central.

To view recordings and slides from past sessions, click on the linked title.

| TOPIC | DATE | Speaker |
| ------------- | --------------- | ----------------- |
| [<span style="color:blue">Working with multidimensional datasets in xarray</span>](/tools/rdm#xarray) | Sep-30 | Alex Razoumov |
| [<span style="color:blue">Intermediate VMD topics: trajectories, movies, scripting</span>](/tools/visualization/#intermediate-vmd-topics-trajectories-movies-scripting) | Oct-28 | Olivier Fisette |
| [<span style="color:blue">Tips & tricks on getting programming help</span>](/getting-started) | Nov-13[^1] | Marie-Hélène Burle |
| [<span style="color:blue">The Topology ToolKit</span>](/tools/visualization/#the-topology-toolkit-ttk) | Nov-25 | Alex Razoumov |
| [<span style="color:blue">Basics of GIS mapping in R</span>](/domains/geo/#gis-with-r) | Dec-09 | Marie-Hélène Burle |

[^1]: Note the different day of the week (Friday).

<!-- ========================================================================================== -->

## Other workshops

| Event | DATE | Location |
| ------------- | --------------- | ----------------- |
| [Scientific Python ](https://libcal.library.ubc.ca/calendar/vancouver/westgrid-scientific-Python) | Sep-22 | <span style="color:#049A80">online for UBC Research Commons</span> |
| [3D scientific visualization with Python scripting in ParaView](https://libcal.library.ubc.ca/event/3578757) | Nov-19 | <span style="color:#049A80">online for UBC Research Commons</span> |
| WestGrid Autumn School | Nov 2-3, 9-10, 16-17, 23-24 | <span style="color:#E26D00">online</span> |
| [Collaborating on GitHub](https://libcal.library.ubc.ca/calendar/vancouver/collaborating-with-git) | Nov-26 | <span style="color:#049A80">online for UBC Research Commons</span> |

<!-- November[^1] -->
<!-- [^1]: Exact dates TBA. -->

<!-- You might also find useful the following workshops taught by our partner Advanced Research Computing -->
<!-- (ARC) teams at the WestGrid member institutions: -->
<!-- * [Hands-on introduction to HPC](https://wiki.usask.ca/x/OgExY) at USask -->
<!-- * [Research Computing Bootcamps](https://ist.ualberta.ca/blog/events/research-computing-bootcamps-are-back) at UofA -->

<!-- ========================================================================================== -->

<!-- As always, we welcome requests for other training topics and events. Please email suggestions to training@westgrid.ca. -->
