---
title: "Events for fall 2023"
aliases:
  - /fall-2023
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

<!-- While WestGrid ceased its operations on March 31, 2022, research computing training in Western Canada remains -->
<!-- -- coordinated by the same team, now based at Simon Fraser University, with participation from HPC analysts -->
<!-- across the BC DRI Group and the Prairies DRI Group (former WestGrid space). -->

To receive future news and emails about the BC DRI Group and the Prairies DRI Group training events, please
[subscribe here](/contact).

[Table of Contents](#table-of-contents):
&nbsp;
[<em>Webinars</em>](#webinars)
• [<em>Online courses</em>](#online-courses)
• [<em>SFU / UBC Research Commons workshops</em>](#commons)
• [<em>Other local bootcamps and workshops</em>](#bootcamps)
<!-- • [<em>Humanities and social sciences training</em>](#dh) -->
• [<em>In-person schools</em>](#schools)

## [Webinars]{#webinars}

BC DRI + Prairies DRI bi-weekly Research Computing webinars take place every second Tuesday at 11am Pacific /
noon Mountain / 1pm Central.

| TOPIC | DATE | SPEAKER |
| ------------- | --------------- | ----------------- |
| [<span style="color:blue">Launching 2023 *Visualize This* contest</span>](/tools/visualization#launching-2023-visualize-this-contest) | Sep-19 | Alex Razoumov (SFU) |
| [<span style="color:blue">A map of current machine learning frameworks</span>](/tools/ml#current-ml-frameworks) | Oct-03 | Marie-Hélène Burle (SFU) |
| [<span style="color:blue">Image-based approach to large-scale visualization</span>](/tools/visualization#cinema) | Oct-17 | Alex Razoumov (SFU) |
| [<span style="color:blue">Essentials of High-Performance Computing for new users: A practical example using hydrological models</span>](/domains/geo#hydrological) | Oct-31 | Marcos Cunha-Cordeiro and Befekadu Woldegiorgis (Univ. of Manitoba) |
| [<span style="color:blue">Emacs as a programming IDE for Python, R, and Julia</span>](/getting-started#emacs) | Nov-14 | Marie-Hélène Burle (SFU) |
| [<span style="color:blue">Text analysis in 3D</span>](/domains/dh/#text-analysis-in-3d) | Nov-28 | Alex Razoumov (SFU) |
| [<span style="color:blue">Version control for data science and machine learning with DVC</span>](/tools/rdm/#dvc) | Dec-12 | Marie-Hélène Burle (SFU) |

## [Online courses]{#courses}

We offer weekly online sessions on advanced research computing. These sessions take place every Thursday from
10am to noon Pacific and are open to all academic researchers across Canada. Most courses span 3 weeks,
although some courses may be shorter or longer.

Please note that these sessions are not recorded, as we want to encourage attendance and live interaction, and
we are planning to repeat the most popular / introductory sessions throughout the year.

| COURSE | DATES | INSTRUCTOR |
| ------------------ | --------------- | ----------------- |
| <span style="color:gray">Introduction to Bash command line</span> | Sep-14, Sep-21 | Marie-Hélène Burle, <br> Alex Razoumov |
| <span style="color:gray">Scientific Python</span> | Sep-28, Oct-05 | Alex Razoumov |
| <span style="color:gray">Speeding up computations in R</span> | Oct-12, Oct-26, <br>Nov-02 | Marie-Hélène Burle |
| <span style="color:gray">Parallel computing in Chapel</span> | Nov-09, Nov-16 | Alex Razoumov |
| <span style="color:gray">Fast computing with JAX</span> | Nov-30, Dec-07 | Marie-Hélène Burle |
| <span style="color:gray">Introduction to Bash command line</span> | Dec-14, Dec-21 | Marie-Hélène Burle, <br> Alex Razoumov |

## [SFU / UBC Research Commons workshops]{#commons}

This fall the SFU workshops will be taught in-person, and the UBC workshops will be online via Zoom. To
register, click on an event in the 3rd or 4th column. Students, staff and faculty are all welcome to attend.

| TOPIC | SPEAKER | 1st RUN | 2nd RUN |
|-|-|-
| Introduction to Python (basic concepts and data structures) | Marie-Hélène Burle and Alex Razoumov | [Friday, Sep-29 at <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/38182){target="_blank"} | [Friday, Oct-06 at <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3748911){target="_blank"} |
| Introduction to scientific Python (numpy, pandas, xarrays) | Marie-Hélène Burle and Alex Razoumov | [Friday, Oct-20 at <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/38183){target="_blank"} | [Friday, Oct-27 at <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3748918){target="_blank"} |
| Python for simple data visualization | Marie-Hélène Burle and Alex Razoumov | [Friday, Nov-17 at <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/38184){target="_blank"} | [Friday, Nov-24 at <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3748919){target="_blank"} |
| Web scraping with Python | Marie-Hélène Burle and Alex Razoumov | [Friday, Dec-01 at <span style="color:#CE0834">SFU Research Commons</span>](https://www.lib.sfu.ca/about/branches-depts/rc/software-data-dh/software/38185){target="_blank"} | [Friday, Dec-08 at <span style="color:#005CA7">UBC Research Commons</span>](https://libcal.library.ubc.ca/event/3748920){target="_blank"} |

## [Local bootcamps and workshops]{#bootcamps}

We will be adding workshops here as they are announced at other Western Canadian universities.

| EVENT | DATE | VENUE |
| ------ | ---- | ---- |
| [Univ. of Alberta Fall Bootcamp](https://www.ualberta.ca/information-services-and-technology/news/2023/fall-research-computing-bootcamp.html){target="_blank"} | Starts Sep-22 | Online |

<!-- watch https://www.ualberta.ca/information-services-and-technology/research-computing -->

<!-- <a name="dh"></a> -->
<!-- ## Humanities and social sciences training -->

<!-- | DATE | EVENT | VENUE | -->
<!-- | Feb-14 to Feb-17 | [HSS Winter Series](https://hss23.netlify.app){target="_blank"} | online | -->
<!-- | June 5-9 and 12-16 | [DHSI](https://dhsi.org){target="_blank"} <br> (Digital Humanities Summer Institute) | TBC | -->

## [In-person schools]{#schools}

<!-- | DATE | COURSE | LOCATION | -->
<!-- | May 1-5 <br> (5 days) | [UVic spring school](https://2023uvic.netlify.app){target="_blank"} | UVic | -->
<!-- | June 19-23 <br> (5 days) | [SFU summer school](https://2023sfu.netlify.app){target="_blank"} | SFU's Big Data Hub | -->

<br>
As always, we welcome requests for other training topics and events. Please email suggestions to `training at
westdri dot ca`.
