---
title: "Events for fall 2026"
aliases:
  - /fall-2026
toc: false
---

<style>
table {
  max-width: 90%;;
  margin: 0 auto;
}
h2 {
  color: midnightblue;
}
</style>

<!-- deployment status https://github.com/WestGrid/trainingMaterials/actions -->

To receive future news and emails about our training events, please [subscribe here](/contact).

<!-- To receive future news and emails about the BC DRI Group and the Prairies DRI Group training events, please -->
<!-- [subscribe here](/contact). -->

[Table of Contents](#table-of-contents):
&nbsp;
[<em>Webinars</em>](#webinars)
• [<em>Online courses</em>](#courses)
• [<em>Other local bootcamps and workshops</em>](#bootcamps)

## [Webinars]{#webinars}

The 2026 Fall Webinars, hosted by SFU's Research Computing Group (RCG), will take place every second Tuesday
at 10:00am Pacific Time ([convert to your
timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Webinar&iso=20261015T1000&p1=137){target="_blank"}).

<!-- Webinar details and registration links will be posted here in March. -->

For *upcoming webinars*, click the linked titles to view details or register. For *past sessions*, click the
titles to access recordings and slides.

| TOPIC | DATE | SPEAKER |
| ----------- | ---- | ------- |
| [3D data processing and visualization with PyVista](https://forms.gle/ADAeeH38oxeRYkKj8) | Sep-29 | Alex Razoumov |
| [Hardening your system in the age of AI](https://forms.gle/mNfAVjb8UUHVdfDh7) | Oct-13 | Marie-Hélène Burle |
| [Concepts of NLP](https://forms.gle/LzzZnTie1beHC2Tr9) | Oct-27 | Marie-Hélène Burle |
| [Why would you use Rust for scientific computing?](https://forms.gle/tYgFGUPdoPAuAbfd8) | Nov-10 | Manuel Sebastian Drehwald (NVIDIA) | <!-- Marie vacation Nov-09-13 -->
| [Scalable numerical methods](https://forms.gle/kQpAYLdgkKAMknvXA) | Nov-24 | Sarah Huber (UVic) |
| [Productivity meets performance: domain-decomposed stencils in MPI and Chapel](https://forms.gle/u7XZYT3vzs8dh1Mw8) | Dec-08 | Alex Razoumov |

## [Online courses]{#courses}

SFU Research Computing hosts weekly online sessions on advanced computational topics every Thursday from
10:00am ([convert to your
timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Webinar&iso=20261015T1000&p1=137){target="_blank"})
to noon Pacific Time. These sessions are open to academic researchers across Canada. Most courses run for two
weeks, although some are shorter or longer. Sessions are not recorded to encourage live participation and
interaction. Popular introductory topics are repeated throughout the year.

<!-- SFU classes start on Wed Sep-09 -->

| TOPIC | DATES | INSTRUCTOR |
| ------------ | ----- | ---------- |
| [Bash for beginners](https://forms.gle/gwZxrVkskX4qYm75A) | Sep-17 | Marie-Hélène Burle |
| [HPC for beginners](https://forms.gle/c5vb26hxoKaoPWpE9) | Sep-24,<br>Oct-01 | Alex Razoumov |
| [Containers for HPC](https://forms.gle/FsBihszQehZx2vuG7) | Oct-08 | Alex Razoumov | <!-- Working with Apptainer containers -->
| [Getting started with Git](https://forms.gle/einS6fRfNFzu8Tzn9) | Oct-15,<br>Oct-22 | Marie-Hélène Burle |
| [Collaboration via GitHub](https://forms.gle/6PVS7yCVQ24dsHTG9) | Oct-29 | Marie-Hélène Burle |
| [HPC Python](https://forms.gle/Bsmn6fsjmR9ZobxH8) | Nov-05,<br>Nov-12 | Alex Razoumov | <!-- Marie vacation Nov-09-13, Calgary training summit Nov-04-06 -->
| [Numba JIT compilation to CUDA kernels](https://forms.gle/ee2N4tem8jKuuKdr9) | Nov-19 | Alex Razoumov |
| [Intro DL with PyTorch](https://forms.gle/aojynRpvB7k8jCYG8) | Nov-26,<br>Dec-03 | Marie-Hélène Burle |
| [Gen-AI with PyTorch for simulation data](https://forms.gle/SXkaJZtdDLxD4rbX9) | Dec-10 | Alex Razoumov |
| [Bring your questions & problems](https://forms.gle/3exrfA37XjVx7ZDx6) | Dec-17 | Marie-Hélène Burle<br>& Alex Razoumov |

<!-- 1. break into smaller courses, with dependencies/requirements -->
<!-- 1. be explicit about pre-requisites, e.g. for this Python course some were not familiar with HPC and bash, no -->
<!--    idea what ssh is, etc. -->
<!-- 1. include into the abstract: if you have not attended, please study this material -->
<!-- 1. two start times: 9:30am for people not familiar with ssh, 10:00am for everyone else -->
<!-- 1. we have 19 weeks - 1 reading week break = 18 weeks, starting on Jan-19 -->

## [Upcoming bootcamps and workshops]{#bootcamps}

Workshops offered by other Western Canadian universities will be added here as they are announced.

<!-- | DATE | EVENT | VENUE | -->
<!-- | ---- | ----- | ----- | -->
<!-- | Jan-Feb | [UofA Winter Bootcamp](https://www.ualberta.ca/en/information-services-and-technology/research-computing/bootcamps.html){target="_blank"} | Online | -->
<!-- | May | [UofA Spring Bootcamp](https://ualbertauw.qualtrics.com/jfe/form/SV_9mGhgrxohgzJc1w){target="_blank"} | Online | -->

<br>
As always, we welcome suggestions for additional training topics and events. Please email your ideas to
`training at westdri dot ca`.
