---
title: "Events for April - July 2018"
aliases:
  - /spring-summer-2018
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

For more information on each session, or to register, click on the links below.

## Webinars

* *Bioinformatics Series: Designing and implementing a variant database* (Apr-11)
*  *Cloud Basics Walkthrough: Logging in and creating a first virtual machine* (Apr-25)
* *A Brief Introduction to the Boost MPI Library* (May-09)
* *Hands-on with the new features in ParaView 5.5* (Jun-06)

## In-person workshops

* [*Software Carpentry at SFU*](https://computecanada.github.io/2018-04-30-sfu) (Apr-30 to May-01)
* *Introduction to Cedar* (Omics@SFU, May-11)
* UNBC workshops in Prince George: *3D visualization*, *Introductory Python*, *Introduction to HPC*, *Parallel programming with Chapel* (May-16 to May-18)
* University of Alberta workshops: [*HPC Carpentry with Chapel*](https://computecanada.github.io/2018-05-28-ualberta-hpc), *3D visualization* (May-28 to May-30)
* DHSI courses at UVic: *3D visualization for the humanities*, *Unleash Linux on MacOS* (Jun-10)
* WestGrid summer school at UBC (Jun-11 to Jun-14)
* WestGrid summer school at the University of Manitoba (Jun-25 to Jun-28)
* *3D visualization* at the 9th Annual Faculty of Engineering Graduate Research Symposium, UofA (Jul-03)

As always, we welcome requests for other training topics and events. Please email suggestions to
info@westgrid.ca.
