---
title: "Events for winter-spring 2020"
aliases:
  - /winter-spring-2020
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

<!-- ========================================================================================== -->

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain
/ 12pm Central.

To view recordings and slides from past sessions, click on the linked title.

| TOPIC | DATE | Speaker |
| ------------- | ------ | ------------ |
| [<span style="color:blue">Photorealistic rendering with ParaView and OSPRay</span>](/tools/visualization#photorealistic-rendering-with-paraview-and-ospray) | Jan-15[^1] | Alex Razoumov |
| [<span style="color:blue">Singularity in HPC: beyond the basics</span>](/tools/virtual#singularity-in-hpc) | Feb-05 | Grigory Shamov |
| [<span style="color:blue">Fun tools to simplify your life in the command line</span>](/getting-started#fun-tools-to-simplify-your-life-in-the-command-line) | Feb-19 | Marie-Hélène Burle |
| [<span style="color:blue">High-performance research computing with Julia</span>](/programming#high-performance-research-computing-with-julia) | Mar-04 | Marie-Hélène Burle |
| [<span style="color:blue">Working with data files and external C libraries in Chapel</span>](/programming#working-with-data-files-and-external-c-libraries-in-chapel) | Mar-18 | Alex Razoumov |
| [<span style="color:blue">Scientific graphics with GNUPlot</span>](/tools/visualization#scientific-graphics-with-gnuplot) | Apr-01 | Dmitri Rozmanov |
| [<span style="color:#049A80">Intro to HPC</span>](https://libcal.library.ubc.ca/calendar/vancouver/intro-hpc) (remote for UBC Research Commons) | Apr-08 | Alex Razoumov |
| [<span style="color:blue">Building software on Compute Canada clusters using EasyBuild</span>](/getting-started#building-software-with-easybuild) | Apr-15 | Ali Kerrache |
| [<span style="color:blue">Web-based 3D scientific visualization</span>](/tools/visualization#web-based-3D-scientific-visualization) | Apr-29 | Alex Razoumov |
| [<span style="color:#049A80">Intro to Cloud Computing</span>](https://libcal.library.ubc.ca/calendar/vancouver/intro-cc-cloud) (remote for UBC Research Commons) | May-06 | pre-recorded |
| [<span style="color:blue">Machine learning in Julia with Flux</span>](/tools/ml#machine-learning-in-julia-with-flux) | May-13 | Marie-Hélène Burle |
| [<span style="color:blue">Mining Twitter data for research (part 2)</span>](/domains/dh#twitterapistwo) | May-27 | John Simpson |

[^1]: Note the off-cycle week.

<!-- John: Let's extend and finalize the Twitter workshop that I ran earlier. In particular I'll: -->
<!-- 1. Generalize what was shared previously so that they can grab even more content than before. -->
<!-- 2. Demonstrate how to use MongoDB as the backend repository for holding the data. -->
<!-- backup webinar: advanved Linux tools (Marie) -->

<!-- ========================================================================================== -->

## In-person workshops

| Event | DATE | Location |
| ------------- | -------- | ----------------- |
| [<span style="color:#049A80">Advanced Unix Shell</span>](https://libcal.library.ubc.ca/event/3540387) | Feb-07 | <span style="color:#049A80">UBC Research Commons</span> |
| [<span style="color:#E26D00">WestGrid Spring School</span>](https://www.eventbrite.ca/e/research-computing-workshops-simon-fraser-university-registration-88799572913) | Mar-2,3,5,6 | <span style="color:#E26D00">Big Data Hub @SFU</span> |
| WestGrid workshop at BMIAI@UBC | Mar-09 | UBC |
| [<span style="color:#049A80">Advanced GitHub</span>](https://libcal.library.ubc.ca/event/3540388) | Mar-13 | <span style="color:#049A80">UBC Research Commons</span> |
| <span style="color:#E26D00"><b>WestGrid Summer School</b></span> | TBA | <span style="color:#E26D00">online</span> |

<!-- | Jun-07 | [3D Visualization for the Humanities](https://dhsi.org/course-offerings) | DHSI @UVic | -->
<!-- | Jun-08-12 | [Fundamentals of Programming for Human(s,ists)](https://dhsi.org/course-offerings) | DHSI @UVic | -->

You might also find useful the following workshops taught by our partner Advanced Research Computing
(ARC) teams at the WestGrid member institutions:

* [Hands-on introduction to HPC](https://wiki.usask.ca/x/OgExY) at USask
* [Research Computing Bootcamps](https://ist.ualberta.ca/blog/events/research-computing-bootcamps-are-back) at UofA

<!-- ========================================================================================== -->

As always, we welcome requests for other training topics and events. Please email suggestions to info at
westgrid dor ca.
