---
title: "Events for winter-spring 2021"
aliases:
  - /winter-spring-2021
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

<!-- ========================================================================================== -->

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain / 12pm Central.

To view recordings and slides from past sessions, click on the linked title.

| TOPIC | DATE | Speaker |
| ------------- | --------------- | ----------------- |
| [<span style="color:blue">Workflows with Programmable Filter / Source in ParaView</span>](/tools/visualization/#programmable) | Jan-20 | Alex Razoumov |
| [<span style="color:blue">Advanced GIS mapping in R</span>](/domains/geo/#advanced-gis-mapping-in-r) | Feb-03 | Marie-Hélène Burle |
| [<span style="color:blue">Automating your backups in Linux and MacOS</span>](/tools/rdm/#backups) | Feb-17 | Alex Razoumov |
| [<span style="color:blue">Linking databases to code repositories with Throughput</span>](/tools/rdm/#throughput) | Mar-03 | Simon Goring |
| [<span style="color:blue">Parallel Julia</span>](/programming/#julia) | Mar-17 | Alex Razoumov and Marie-Hélène Burle |
| [<span style="color:blue">Exploring the state of a Slurm cluster with Clusterstats</span>](/tools/scheduling/#exploring-the-state-of-a-slurm-cluster-with-clusterstats) | Mar-31 | Kamil Marcinkowski |
| [<span style="color:blue">Introduction to deep learning with fastai</span>](/tools/ml#fastai) | Apr-14 | Marie-Hélène Burle |
| [<span style="color:blue">Scientific visualization on NVIDIA GPUs</span>](/tools/visualization/#nvidia) | Apr-28 | Nick Leaf (NVIDIA) |
| [<span style="color:blue">Exploration of tools and approaches for Humanists</span>](/domains/dh/#exploration) | May-12 | Megan Meredith-Lobay |
| [<span style="color:blue">Using Singularity containers in VMs and HPC</span>](/tools/virtual/#venkatSingularity) | May-26 | Venkat Mahadevan |

<!-- Nov-13[^1] -->
<!-- [^1]: Note the different day of the week (Friday). -->

<!-- ========================================================================================== -->

## Other workshops

| Event | DATE | Location |
| ------------- | --------------- | ----------------- |
| [Tips & tricks on getting programming help online](https://libcal.library.ubc.ca/calendar/vancouver/finding-technical-help-online) | Jan-14 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [Automating your backups in Linux and MacOS](https://libcal.library.ubc.ca/calendar/vancouver/unix-backups) | Feb-11 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [Compute Canada's Humanities and Social Sciences series](https://hss-series.netlify.app) | Feb-16 to Feb-19 | <span style="color:#0033cc">Online</span> |
| [NVIDIA GPU Hackathon @SFU](https://www.gpuhackathons.org/event/simon-fraser-university-gpu-hackathon) | Feb-22 to Mar-03 | <span style="color:#0033cc">Online</span> |
| Workshops for the GIWS @USask | Mar-29 to Mar-30 | Online |
| [Basics of GIS mapping in R](https://libcal.library.ubc.ca/calendar/vancouver/gis-mapping-r) | Apr-08 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [Spatial Analysis/GIS in R](https://www.eventbrite.ca/e/introduction-to-gis-spatial-analysis-in-r-registration-148848631263) | Apr-26 | UBC |
| [Parallel programming in Julia](https://libcal.library.ubc.ca/calendar/vancouver/parallel-programming-julia) | May-13 | <span style="color:#049A80">Online for UBC Research Commons</span> |
| [WestGrid training modules 2021](https://wgtm21.netlify.app) | Apr-27 to Jul-27 | <span style="color:#0033cc">Online</span> |

<!-- November[^1] -->
<!-- [^1]: Exact dates TBA. -->



<!-- You might also find useful the following workshops taught by our partner Advanced Research Computing -->
<!-- (ARC) teams at the WestGrid member institutions: -->
<!-- * [Hands-on introduction to HPC](https://wiki.usask.ca/x/OgExY) at USask -->
<!-- * [Research Computing Bootcamps](https://ist.ualberta.ca/blog/events/research-computing-bootcamps-are-back) at UofA -->

<!-- ========================================================================================== -->

<!-- As always, we welcome requests for other training topics and events. Please email suggestions to training@westgrid.ca. -->
