---
title: "Events for winter-spring 2019"
aliases:
  - /winter-spring-2019
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

For more information on each session, or to register, click on the links below.

## Webinars

WestGrid's bi-weekly training webinars take place every second Wednesday at 10am Pacific / 11am Mountain
/ 12pm Central.

To view recordings and slides from past sessions, click on the linked title.

| TOPIC | DATE | Speaker |
| ------------- | -------- | ----------------- |
| [Working with data objects in yt](/tools/visualization#yt2) (visualization) | Jan-23 | Alex Razoumov |
| [Text Parsing and Analysis with HPC](/domains/dh#textParsing) | Feb-06 | Ian Percel |
| [Memory debugging with Valgrind](/programming#debugging-and-memory-debugging) | Feb-20 | Tyson Whitehead (SHARCNET) |
| [Molecular visualization with VMD](/tools/visualization#molecular-visualization-with-vmd) | Mar-06 | Dmitri Rozmanov |
| [Research Data Management Tools, Platforms, and Best Practices for Canadian Researchers](/tools/rdm#rdmToolsPlatforms) | Mar-20 | Alex Garnett (SFU) and Adam McKenzie |
| [Short read DNA sequencing alignment and visualization](/domains/bioinfo#short-read-DNA-sequencing-alignment-and-visualization) | Apr-03 | Phillip Richmond (UBC) |
| [Computing graphs on an HPC cluster: working with distributed unstructured data in Chapel](/programming#chapel) | Apr-17 | Alex Razoumov |
| [Learn how to manage many files with DAR disk archiver](/tools/rdm#dar) | May-01 | Alex Razoumov |

## In-person workshops

| Event | DATE | Location |
| ------------- | ------ | --------- |
| Research Computing Workshops: *Introduction to Scientific Computing with Linux, High-Performance Computing, Parallel Programming, and Scientific Visualization* | Jan-15 to Jan-18 | University of Saskatchewan |
| [Research Computing Winter Bootcamp](https://ist.ualberta.ca/blog/news/get-ready-research-computing-winter-bootcamp) | Jan-28 to Feb-01 | University of Alberta |
| [Python-themed Software Carpentry](https://computecanada.github.io/2019-02-04-sfu) | Feb-04 to Feb-05 | SFU |
| [Research Computing Workshops: *Introduction to Scientific Computing with Linux, High-Performance Computing, Parallel Programming, and Scientific Visualization*](https://www.eventbrite.ca/e/research-computing-workshops-simon-fraser-university-big-data-hub-registration-56308425015) | Mar-18 to Mar-21 | SFU |
| [Using yt for analysis and visualization of volumetric data in Python](https://github.com/sciprog-sfu/sciprog-sfu.github.io/issues/200) | Apr-30 | SFU |
| [Research Computing Spring Bootcamp](https://ist.ualberta.ca/blog/news/get-ready-research-computing-spring-bootcamp) | Apr-29 to May-03 | University of Alberta |
| [Research Computing Summer School](http://bit.ly/calgarySchool19) | May-27 to May-30 | University of Calgary |
| [Research Computing Summer School](http://bit.ly/ubcSchool19) | June-24 to June-27 | University of British Columbia |

As always, we welcome requests for other training topics and events. Please email suggestions to info at
westgrid dot ca.
