---
title: "Events for winter-spring 2026"
aliases:
  - /winter-spring-2026
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

To receive future news and emails about our training events, please [subscribe here](/contact).

<!-- To receive future news and emails about the BC DRI Group and the Prairies DRI Group training events, please -->
<!-- [subscribe here](/contact). -->

[Table of Contents](#table-of-contents):
&nbsp;
[<em>Winter Visualization Series</em>](#winter-series)
• [<em>Webinars</em>](#webinars)
• [<em>Online courses</em>](#courses)
• [<em>Other local bootcamps and workshops</em>](#bootcamps)
<!-- • [<em>Humanities and social sciences training</em>](#dh) -->
• [<em>Summer school</em>](#schools)

## [Summer school]{#schools}

<!-- Typically at the end of a term we organize a longer, in-person research computing school at SFU that is open -->
<!-- to all students, postdocs, faculty and staff. We will add more information here. -->

SFU's 2026 Research Computing Summer School will run June 1–5 as a week-long, in-person program open to
researchers at SFU and other Canadian post-secondary institutions. For details and the full schedule, please
visit the [school website](https://sfu26.netlify.app){target="_blank"}.

## [Winter Visualization Series]{#winter-series}

This year, [the National Visualization Team](https://ccvis.netlify.app){target="_blank"} is hosting the Winter
Visualization Series, featuring 18 workshops running from January 20 to March 27. For full details and
registration, please visit [the Series webpage](https://folio.vastcloud.org/winterseries){target="_blank"}.

## [Webinars]{#webinars}

To accommodate the Winter Visualization Series, our webinar season will begin on April 7, 2026. The 2026
Spring Webinars, hosted by SFU's Research Computing Group (RCG), will take place every second Tuesday at
10:00am Pacific (Victoria, Vancouver), 11:00am Mountain (Edmonton, Calgary), and 12:00pm Central
(Winnipeg).

<!-- Webinar details and registration links will be posted here in March. -->

For *upcoming webinars*, click the linked titles to view details or register. For *past sessions*, click the
titles to access recordings and slides.

| TOPIC | DATE | SPEAKER |
| ----- | ---- | ------- |
| [<span style="color:blue">RIP pandas, welcome Polars</span>](/tools/rdm) | Apr-07 | Marie-Hélène Burle |
| [<span style="color:blue">Typst: a new markup typesetting system</span>](/getting-started#author) | Apr-21 | Marie-Hélène Burle |
| [<span style="color:blue">OpenStack command line in action: VMs in minutes</span>](/tools/virtual) | May-05 | Alex Razoumov |
| [<span style="color:blue">Two paths to Python dashboards: Shiny vs Dash</span>](/tools/visualization) | May-19 | Marie-Hélène Burle<br>& Alex Razoumov |

## [Online courses]{#courses}

SFU Research Computing hosts weekly online sessions on advanced research computing every Thursday from 10:00am
to noon Pacific Time. These sessions are open to all academic researchers in Canada. Most courses span two
weeks, though some may be shorter or longer. Sessions are not recorded to encourage live participation and
interaction. Popular and introductory sessions are repeated throughout the year.

| COURSE | DATES | INSTRUCTOR |
| ---------------- | -------- | ---------- |
| Bash for beginners | Jan-22 | Marie-Hélène Burle |
| HPC for beginners | Jan-29 | Alex Razoumov |
| Introduction to Python | Feb-05, Feb-12,<br>Feb-26 | Marie-Hélène Burle |
| Getting started with Git | Mar-05 | Marie-Hélène Burle |
| Collaboration with GitHub | Mar-12 | Marie-Hélène Burle |
| Parallel computing in Julia | Mar-19, Mar-26 | Alex Razoumov |
| Parallel computing in Chapel | Apr-02 | Alex Razoumov |
| GPU Python:<br>Arrays with CuPy | Apr-09 | Marie-Hélène Burle |
| GPU Python:<br>Numba JIT compilation to CUDA kernels | Apr-16 | Alex Razoumov |
| GPU Python:<br>DataFrames with Polars and RAPIDS cuDF | Apr-23 | Marie-Hélène Burle |
| GPU programming in Chapel | Apr-30 | Alex Razoumov |
| Gen-AI with JAX for simulation data | May-07 | Alex Razoumov |
| High-performance R | May-14, May-21 | Marie-Hélène Burle |

<!-- fall 2026 courses: -->
<!-- Marie 2-week Getting started with Git (1 week is not enough) followed by 1-week Collaboration with Git -->
<!-- Marie 3-week PyTorch course (back from JAX) -->

<!-- 1. break into smaller courses, with dependencies/requirements -->
<!-- 1. be explicit about pre-requisites, e.g. for this Python course some were not familiar with HPC and bash, no -->
<!--    idea what ssh is, etc. -->
<!-- 1. include into the abstract: if you have not attended, please study this material -->
<!-- 1. two start times: 9:30am for people not familiar with ssh, 10:00am for everyone else -->
<!-- 1. we have 19 weeks - 1 reading week break = 18 weeks, starting on Jan-19 -->

<!-- |COURSE|WINTER/SPRING 2024|FALL 2024|WINTER/SPRING 2025|FALL 2025| -->
<!-- |Introduction to the Unix shell|X||X|X| -->
<!-- |Introduction to HPC|X|X|X|X| -->
<!-- |Introduction to Python||||X| -->
<!-- |Getting started with Git|X|X||X| -->
<!-- |Working with Apptainer containers|X|X||X| -->
<!-- |HPC Python|X|X|X|X| -->
<!-- |High-performance R|||X|| -->
<!-- |Parallel Julia|X||X|| -->
<!-- |Parallel programming in Chapel|||X|| -->
<!-- |Using GPUs with Chapel||X||| -->
<!-- |Deep learning with JAX|X||X|X| -->
<!-- |Deep learning with Flax|X|||| -->
<!-- |Beginner's introduction to Emacs||X||| -->
<!-- |Faster Python DataFrames with Polars||X||| -->
<!-- |Answering your Bash questions||X||| -->
<!-- |Scientific visualization|X||X|X| -->
<!-- |Large-scale and remote visualization|X|X||| -->
<!-- |Hands-on with ParaView’s Programmable Filter/Source for scientific visualization||X||| -->

## [Bootcamps and workshops]{#bootcamps}

Workshops from other Western Canadian universities will be added here as they are announced.

| EVENT | DATE | VENUE |
| ----- | ---- | ----- |
| [UofA Winter Bootcamp](https://www.ualberta.ca/en/information-services-and-technology/research-computing/bootcamps.html){target="_blank"} | Jan-Feb | Online |
| [UofA Spring Bootcamp](https://ualbertauw.qualtrics.com/jfe/form/SV_9mGhgrxohgzJc1w){target="_blank"} | May | Online |

---

<br>
As always, we welcome suggestions for additional training topics and events. Please email your ideas to
`training at westdri dot ca`.
