---
title: "Events for winter-spring 2024"
aliases:
  - /winter-spring-2024
toc: false
---

<style>
/* Adjust table width */
table {
  max-width: 90%;;
  margin: 0 auto;
}
</style>

To receive future news and emails about the BC DRI Group and the Prairies DRI Group training events, please
[subscribe here](/contact).

[Table of Contents](#table-of-contents):
&nbsp;
[<em>Webinars</em>](#webinars)
• [<em>Online courses</em>](#courses)
• [<em>In-person schools</em>](#schools)
• [<em>Other bootcamps and workshops</em>](#bootcamps)
<!-- • [<em>Humanities and social sciences training</em>](#dh) -->

## [Webinars]{#webinars}

BC DRI + Prairies DRI bi-weekly Research Computing webinars take place every second Tuesday at 11am Pacific /
noon Mountain / 1pm Central.

<!-- Webinar registration will open in early September. -->

<!-- For *upcoming webinars*, click the linked title to see more details or to register. For *past -->
<!-- sessions*, click on the title to view recordings and slides. -->

| DATE | TOPIC | SPEAKER |
| ------------- | --------------- | ----------------- |
| Jan-09 | [<span style="color:blue">Command-line image processing with ImageMagick</span>](/tools/visualization#imagemagick) | Alex Razoumov (SFU) |
| Jan-23 | [<span style="color:blue">AI-powered coding with GitHub Copilot</span>](/tools/ml#copilot) | Marie-Hélène Burle (SFU) |
| Feb-20 | [<span style="color:blue">Photogrammetry on HPC clusters</span>](/domains/dh/#photogrammetry) | Alex Razoumov (SFU) | <!-- Marie away this week -->
| Mar-05 | [<span style="color:blue">Modern Emacs: all those new tools that make Emacs better and faster</span>](/getting-started#emacs) | Marie-Hélène Burle (SFU) |
| Mar-19 | [<span style="color:blue">Things researchers should know before using Generative AI</span>](/tools/ml#genai) | Jillian Anderson (SFU) |
| Apr-16 | [<span style="color:blue">JAX: a framework for high-performance array computing</span>](/tools/ml#jax) | Marie-Hélène Burle (SFU) |
| Apr-23 | [<span style="color:blue">Lossy data compression</span>](/tools/rdm#lossy) | Alex Razoumov (SFU) | <!-- topological or ML -->
| Apr-30 | [<span style="color:blue">Julia at full tilt: profiling and optimizations</span>](/programming#julia) | Paul Schrimpf (UBC) |
| May-14 | [<span style="color:blue">DataFrames on steroids with Polars</span>](/tools/rdm#polars) | Marie-Hélène Burle (SFU) |

## [Online courses]{#courses}

We offer weekly online sessions on advanced research computing. These sessions take place every Thursday from
10am to noon Pacific and are open to all academic researchers across Canada. Most courses span 2 weeks,
although some courses may be shorter or longer.

Please note that these sessions are not recorded, as we want to encourage attendance and live interaction, and
we are planning to repeat the most popular / introductory sessions throughout the year.

| COURSE | DATES | INSTRUCTOR |
| -------------------- | ------------ | ----------------- |
| <span style="color:gray">Introduction to HPC</span> | Jan-11, Jan-18 | Alex Razoumov |
| <span style="color:gray">Introduction to Apptainer containers</span> | Jan-25 | Alex Razoumov |
| <span style="color:gray">Parallel computing in Julia</span> | Feb-01, Feb-08 | Alex Razoumov |
| <span style="color:gray">3D scientific visualization with ParaView</span> | Feb-22, Feb-29 | Alex Razoumov |
| <span style="color:gray">Introduction to Bash command line</span> | Mar-07, Mar-14 | Marie-Hélène Burle and Alex Razoumov |
| <span style="color:gray">Version control with Git</span> | Mar-21 | Marie-Hélène Burle |
| <span style="color:gray">Parallel computing in Python</span> | Mar-28, Apr-04 | Alex Razoumov |
| <span style="color:gray">Introduction to JAX: a framework for high-performance array computing and automatic differentiation</span> | Apr-11, Apr-18, <br>Apr-25 | Marie-Hélène Burle |
| <span style="color:gray">Introduction to deep learning with Flax, a neural network framework built on JAX</span> | May-02, May-09, <br>May-16 | Marie-Hélène Burle |
| <span style="color:gray">Large-scale and remote visualization</span> | May-23 | Alex Razoumov |

<!-- Part 1: JAX fundamentals (3 weeks) -->
<!--         - week 1: intro to JAX (why JAX, relation to NumPy) -->
<!--         - week 2: JIT and AD -->
<!--         - week 3: Pytrees and parallel execution -->
<!-- Part 2: Deep learning with JAX and Flax (3 weeks) -->
<!--         - week 1: intro to deep learning and Flax -->
<!--         - week 2: Flax fundamentals -->
<!--         - week 3: Data preprocessing and training techniques, and Parallel training -->

<!-- | HSS Winter Series week | Feb-15 | | -->

## [2024 summer school]{#schools}

SFU's Research Computing 2024 Summer School will be held on June 3-7 (full week), organized in collaboration
with [the Institute for Neuroscience and Neurotechnology](https://www.sfu.ca/neuro-institute.html){target="_blank"} and
hosted by [SFU's Big Data Hub](https://www.sfu.ca/big-data.html){target="_blank"}. It is open to all academic
researchers at SFU, UBC, BCIT and other local post-secondary institutions. Researchers of all levels --
undergraduate and graduate students, postdocs, faculty and staff -- are welcome to register.

You can find more details including the program on the [school website](https://rcss24.netlify.app/){target="_blank"},
and you can register [here](https://www.eventbrite.ca/e/881514191677){target="_blank"}.

Note that our colleagues at UBC are organizing an in-person summer school in July (linked in the table below)
that will have some courses that we do not cover at SFU.

## [Bootcamps and workshops]{#bootcamps}

We will be adding workshops here as they are announced at other Western Canadian universities.

| DATE | EVENT | VENUE |
| ---- | ----- | ----- |
| Starts Jan-19 | <span style="color:gray">Univ. of Alberta Winter Bootcamp</span> | Online |
| Feb 12-16 | <span style="color:gray">HSS Winter Series 2024</span> | Online |
| Feb 26-28 | <span style="color:gray">Introduction to programming with Python (follow-up to the 2024 HSS Winter Series)</span> | Online |
| Feb 26-28 | <span style="color:gray">Introduction to programming with R (follow-up to the 2024 HSS Winter Series)</span> | Online |
| Starts Apr-30 | [Univ. of Alberta Spring Bootcamp](https://www.ualberta.ca/information-services-and-technology/news/2024/spring-research-computing-bootcamp-2024.html){target="_blank"} | Online |
| Jul 8-11 | [UBC ARC 2024 Summer School](https://arc.ubc.ca/training-resources/training-events/arc-2024-summer-school-program-8-11-july-2024){target="_blank"} | West Mall Swing Space |

<!-- watch https://www.ualberta.ca/information-services-and-technology/research-computing -->

<!-- <a name="dh"></a> -->
<!-- ## Humanities and social sciences training -->

<!-- | DATE | EVENT | VENUE | -->
<!-- | Feb-14 to Feb-17 | [HSS Winter Series](https://hss23.netlify.app){target="_blank"} | online | -->
<!-- | June 5-9 and 12-16 | [DHSI](https://dhsi.org){target="_blank"} <br> (Digital Humanities Summer Institute) | TBC | -->

---

<br>
As always, we welcome requests for other training topics and events. Please email suggestions to `training at
westdri dot ca`.
